### PR TITLE
Updated StackPlot.R

### PR DESCRIPTION
**Pull request by idaElken**
Updated StackPlot.R
    -implemented the use of Files (as in PlotCNVs.R) including adding Files, recursive and pattern.
    -the plots are being drawn with Files.
    But when using the Files-option, it writes:
    [126] "NO intensity files exists called: NA" for the number of files in Files
    (after plotting all samples)
    I have not been able to resolve this but the script does the job anyways...

### CODE REVIEW

**Comment by hilge** [comment]
Hi Ida. I will try to have a look at why that error shows up. And have a go at plotting using files.

**Comment by idaElken** [comment]
Thanks :-)

**Comment by idaElken** [comment]
BTW - if you're looking at the code anyways, you may want to consider changing the order of the BAF&LRR for BAF to be on top - then it is in the same way as in PlotCNVs (and personally for one reason or the other, this seems more intuitive)

**Comment by hilge** [comment]
Will do :+1:

**Comment by idaElken** [comment]
Og nu fik jeg øje på en ting mere. 

Når man definerer både Position of plot og highlight og CNV's start eller slutpunkt er uden for plottet, så indtegnes den ikke.

Fx: 
[1] "Position of plot:chr9:700000-1070000"art:	831690	Stop:	959090 
[1] "Highlight:chr9:831690-959090"

       ID Chr  Start   Stop NumSNPs Length  State CN
1 PABWBWZ   9 572371 870777     160 298407 state5  3

9p24 3_chr9-700000-1070000_page-1

Jeg ved ikke, om det drejer sig om kombinationen af Highlight og Pos eller noget andet. 
For øjeblikket er det ikke noget, som er vigtigt nok (for mig) til, at jeg vil gøre noget ved det.

**Comment by mbertalan** [comment]
Hej Ida ! That is great. Let's try to keep the chat in English so other people can participate :-D

**Comment by idaElken** [comment]
Sorry, my mistake. I so agree - very seldom that I switch to Danish, don't know why it happened now :-P

When you define Position of plot and highlight and the start and ending-point of the CNV is outside of the plot, the CNV is not drawn

Eg: 
[1] "Position of plot:chr9:700000-1070000"art: 831690 Stop: 959090 
[1] "Highlight:chr9:831690-959090"

Not sure whether it's the combination of Highlight and Pos or something common to all plots. For the moment it's not important enough for me to do anything about it - just wanted to point the rest of you to it in case someone wants to correct it.

**Comment by hilge** [comment]
I will have a look at that as well. Tomorrow or first thing next week.

**Comment by idaElken** [comment]
Hi Johan, 

A bit of an update on the NA-issue. It seems to have something to do with the way the  "while"-loop runs...
  while(x <= length(Ids)){



For example:
Plotting this data frame:
> test_CNVs
                    ROI  Dataset ID_deidentified Chr    Start     Stop NumSNPs  Length  State CN
1: 10_45928700_51582787 TOP_Affy          TOP491  10 47011195 51537240    2038 4526046 state5  3
2: 10_47013328_51582787 TOP_Affy          TOP491  10 47011195 51537240    2038 4526046 state5  3
                                                               File  startsnp    endsnp    conf  Source
1: /Volumes/deCODEdrive/Monster-drive,Decode/RAW_CEL/LRRBAF//TOP491 CN_524389 CN_043923 996.862 PennCNV
2: /Volumes/deCODEdrive/Monster-drive,Decode/RAW_CEL/LRRBAF//TOP491 CN_524389 CN_043923 996.862 PennCNV
   plusimage     ID   CHR CNV_Start CNV_Stop           locus relation Rel_simple dupremove  Chip
1:       yes TOP491 chr10  47011195 51537240 10q11.22-q11.23       NA         NA      none Affy6
2:       yes TOP491 chr10  47011195 51537240 10q11.22-q11.23       NA         NA      none Affy6
   ChipName_checklist Dataset_alt ImagingName OverlapRef OverlapCNV   CNVofInterest DelDup Direction
1:     Affymetrix 6.0    TOP_Affy    TOP_Affy  0.8004910  1.0000000 10q11.22-23_del    Del      risk
2:     Affymetrix 6.0    TOP_Affy    TOP_Affy  0.9900323  0.9995285 10q11.22-23_dup    Dup      risk
   CNV_Cat           Locus
1:   Psych 10q11.22-q11.23
2:   Psych 10q11.22-q11.23

With these individuals
> IndividualstoPlot
[1] TOP491 TOP491
19599 Levels: 10 101 107 108 109 11 110 112 1122 1123 1124 1131 1132 1133 1134 1135 1136 1137 1138 ... TOP99

Using this version of the script:
> ##' Stackplot: Produces stacked plots of CNV calls from multiple samples for a given locus.
> ##'
> ##' For each sample two tracks are plotted representing the Log R Ratio (LRR) and the B Allele Frequency (BAF).
> ##' @title StackPlot
> ##' @param Pos: Position of the loci to plot in the form chr21:1050000-1350000.
> ##' @param IDs: List of IDs to plot
> ##' @param PathRawData: The path to the raw data files contining LRR and BAF values to plot.
> ##' @param CNVs: Data frame containing the CNVs called on the samples.
> ##' @param Highlight: Position of a specific region to be highlighted, in the form chr21:1050000-1350000, default = NULL.
> ##' @param SNPList: Getting chromosome (chr) and position from another source than the RawFile - input should be the full path of the SNPList with columns: Name, Chr, and Position. Any positions from the RawFile will be erased. A PFB-column is also allowed but will be overwritten by the PFB-parameter or exchanged with 0.5, default = NULL.
> ##' @param key: Exchange the ID printed on the plot with a deidentified ID - requires that the CNV data frame contains a column called ID_deidentified, default = NA.
> ##' @param OutFolder: Path for saving outputfiles. Default is current folder
> ##' @param Files: Full path for each sample. You can get it using the command: Files <- list.files(path=PathRawData, pattern=Pattern, full.names=TRUE, recursive=recursive). Then use Files=Files.
> ##' @param Pattern: File pattern in the raw data, default = "*".
> ##' @param Recursive: Logical, Unknown, default = TRUE.
> ##' @return A png plot of the specified loci.
> ##' @author Johan Hilge Thygesen, Ida Elken Sønderby, Louise K. Hoeffding.
> ##' @source \url{http://biopsych.dk/iPsychCNV}
> ##' @export
> ##' @examples
> ##' mockCNV <- MockData(N=5, Type="Blood", Cores=1)
> ##' cnvs <- iPsychCNV(PathRawData=".", Cores=1, Pattern="^MockSample*", Skip=0)
> ##' StackPlot(Pos="chr21:28338230-46844965", Ids=unique(cnvs$ID), PathRawData=".", CNVs=cnvs, Highlight = "chr21:36653812-39117308")
> 
> StackPlot <- function(Pos, Ids, PathRawData, CNVs, Highlight = NULL, SNPList=NULL, key=NA, OutFolder=".", Files=NA, Pattern="",recursive=TRUE){
+     suppressPackageStartupMessages(library(data.table))
+     options(scipen=999) ## Disable scientific notation of positions
+     
+     ## Check and split position
+     split.pos <- VerifyPos(Pos)
+     chr <- split.pos[1]
+     reg.start <- as.numeric(split.pos[2])
+     reg.stop <- as.numeric(split.pos[3])
+     
+     ## Check ids
+     if(length(Ids) < 1) {
+         stop("Please specify minimum ID")
+     }
+     
+     print("sum of NA-IDs")
+     print(sum(is.na(Ids)))
+     
+     ## Check highlight position if specified
+     if (length(Highlight) > 0){
+         split.pos <- VerifyPos(sub("--highlight ", "", Highlight))
+         high.chr <- split.pos[1]
+         high.start <- as.numeric(split.pos[2])
+         high.stop <- as.numeric(split.pos[3])
+         if(high.chr!=chr){
+             stop("The highlight chromosome does not match the chromosome of the given position")
+         }
+     }
+     
+     ## Plot variables
+     space <- 0.5
+     box <- 1
+     pr.page <- 5
+     datestamp <- gsub(":",".",unlist(strsplit(as.character(Sys.time())," "))[2])
+     if (!is.na(CNVs$Locus[1])) {
+         Locus <- as.character(CNVs$Locus[1])
+         basename <- paste(Locus, "_", "chr",chr,"-",reg.start,"-",reg.stop, sep="")
+     } else {
+         basename <- paste("chr",chr,"-",reg.start,"-",reg.stop, "_at_", datestamp, sep="")
+     }
+     xrange <- range(reg.start,reg.stop)
+     yrange <- range(0, pr.page*(2*box+2*space))
+     x <- 1 # start with id 1
+     i <- 1 # we start with the 1 person on each page
+     page.count <- 1 # start with page 1
+     
+     # Define Files
+     if(is.na(Files))
+     {
+         Files <- gsub("//", "/", list.files(path=PathRawData, pattern=Pattern, full.names=TRUE, recursive=recursive))
+     }
+     
+     
+     ## Loop over each ID and plot away
+     while(x <= length(Ids)){
+         if(OutFolder!=".") {
+             outname <- paste(OutFolder, basename, "_page-", page.count, sep="") }
+         else {
+             outname <- paste(basename, "_page-", page.count, sep="")
+         }
+         png(paste(outname, ".png", sep=""), width=1024, height=768) # can be convertedd to vertical page by switching width and height but requires adjustment of pr.page
+         plot(xrange, yrange, type="n", yaxt='n', xaxt='n', xlab="", ylab="", main = Pos, cex.main=0.6)
+         axis(3, at=axTicks(3),labels=formatC(axTicks(3), format="d", big.mark=','))
+         topY <- max(yrange) - space
+         ## CREATE a new plot after pr.page individuals have been plotted
+         while(i <= pr.page) {
+             print("this is the value of x:")
+             print(x)
+             
+             # Find appropriate file for plotting
+             #     if(is.na(Ids[x])) { # this deals with the issue that the script fails with an error since it does not find NA in Files
+             #       x <- 1 + x
+             #       break
+             #      }else{
+             id.file <- Files[which(Files == paste(PathRawData, Ids[x], Pattern, sep=""))]
+             #        }
+             
+             # Start to plot
+             if(!file.exists(id.file)) {
+                 print(paste("NO intensity files exists called: ", id.file))
+             }else{
+                 print(paste("Plotting",Ids[x]))
+                 
+                 id <- ReadSample(id.file, chr=chr, SNPList = SNPList)
+                 id <- id[which(id[,"Position"] > reg.start & id[,"Position"] < reg.stop), ]
+                 ## Trim intensities to a range between 0.5:-0.5
+                 if(any(id[,"Log.R.Ratio"] > 1, na.rm=T)) { id[which(id[,"Log.R.Ratio"] > 1), "Log.R.Ratio"] <- 1 }
+                 if(any(id[,"Log.R.Ratio"] < -1, na.rm=T)) { id[which(id[,"Log.R.Ratio"] < -1), "Log.R.Ratio"] <- -1 }
+                 ## Set all CN-markers to NA (as they all have the non-usable value of 2) ONLY REALLY FOR AFFY DATA
+                 if(any(id[,"B.Allele.Freq"] == 2, na.rm=T)) { id[which(id[,"B.Allele.Freq"] == 2), "B.Allele.Freq"] <- NA }
+                 ## Define plot area
+                 if(nrow(id) > 1){
+                     
+                     # If key is tagged, the ID in the plot will be a column called ID_deidentified
+                     if (!is.na(key)) {
+                         text(reg.stop-(reg.stop-reg.start)/2, topY + (space/3), paste("ID:",CNVs[CNVs$ID == Ids[x],]$ID_deidentified),lwd=1.5) ## Plot ID name
+                     } else {
+                         text(reg.stop-(reg.stop-reg.start)/2, topY + (space/3), paste("ID:",Ids[x]),lwd=1.5) ## Plot ID name
+                     }
+                     
+                     ## Plot Log R ratio and Intensity boxes
+                     rect(reg.start, topY-box, reg.stop, topY, col="#ffe2e2", border= F)
+                     rect(reg.start, topY-(2*box+(space/2)), reg.stop, topY-(box+(space/2)), col="#e5e2ff", border= F)
+                     ## Draw --Highlight box
+                     if(length(Highlight) > 0) {
+                         segments(high.start, topY-(2*box+(space/2)), high.start, topY, col="black",lwd=1.5) # Start
+                         segments(high.stop, topY-(2*box+(space/2)), high.stop, topY, col="black",lwd=1.5) # Stop
+                     }
+                     
+                     ## Draw all CNV Calls that match alias, chr and fall within region
+                     match <- CNVs[which(CNVs[,"ID"]==Ids[x] & CNVs[,"Chr"] == chr & CNVs[,"Start"] <= reg.stop & CNVs[,"Start"] >= reg.start),]
+                     if(nrow(match)>0) {
+                         ## do not draw cnv boxes outside of plot
+                         if(any(match[,"Start"]<reg.start)) { match[which(match[,"Start"] < reg.start),"Start"] <- reg.start }
+                         if(any(match[,"Stop"]>reg.stop)) { match[which(match[,"Stop"] > reg.stop),"Stop"] <- reg.stop }
+                         for(j in 1:nrow(match)) {
+                             if(match[j,"CN"]>2){ rect(match[j,"Start"],topY-(2*box+(space/2)),match[j,"Stop"],topY,border="#2ef63c",lwd=2) }
+                             if(match[j,"CN"]<2){ rect(match[j,"Start"],topY-(2*box+(space/2)),match[j,"Stop"],topY,border="#ff0000",lwd=2) }
+                         }
+                     }
+                     ## Plot Log R ratio and Intensity points
+                     points(id[,"Position"], id[,"B.Allele.Freq"] + (topY-2*box-(space/2)), pch=20, cex=0.5, col = "darkblue")
+                     points(id[,"Position"], (id[,"Log.R.Ratio"]/2) + (topY-(0.5*box)), pch=20, cex=0.5, col = "darkred")
+                     ## Draw center line in boxs (x0, y0, x1, y1)
+                     segments(reg.start, topY-(box/2), reg.stop, topY-(box/2), col="black")
+                     segments(reg.start, (topY-1.5*box-(space/2)), reg.stop, (topY-1.5*box-(space/2)), col="black")
+                     ## Calc new Y-top spot
+                     topY <- topY-(2*box+1.5*space)
+                     
+                 }else{
+                     print(paste("No data available at this loci for",Ids[x]))
+                 }
+             }
+             ## increment
+             i <- i + 1
+             if(x <= length(Ids)){ x <- 1 + x}
+             else{
+                 break
+             }
+         }
+         page.count <- page.count + 1
+         i <- 1 ## start with person 1 on the first page
+         dev.off()  # gives one png per page
+     }
+ }

Gives this output:
> StackPlot(Pos ="chr10:46011195-52537240", Ids = IndividualstoPlot, CNVs = test_CNVs, key = NA, SNPList = "/Users/idaeson/home/programs/PennCNV-1.0.3/lib/affygw6.hg18.pfb", PathRawData = "/Volumes/deCODEdrive/Monster-drive,Decode/RAW_CEL/LRRBAF/", Highlight = "chr10:47011195-51537240", OutFolder = "/Users/idaeson/Desktop/")
[1] "sum of NA-IDs"
[1] 0
[1] "this is the value of x:"
[1] 1
[1] "Plotting TOP491"
[1] "this is the value of x:"
[1] 2
[1] "Plotting TOP491"
[1] "this is the value of x:"
[1] 3
Error in if (!file.exists(id.file)) { : argument is of length zero

So, apparently the while loop continues for 'too long' - however, I'm not proficient enough in the code to be able to correct it...

Cheers, 
Ida

**Pull request merged**
