### PR TITLE
Updated PlotCNVsFromDataFrame.R with XAxisDefine & Si-measures on 

### PR DESCRIPTION
**Pull request by idaElken**
Looks of plot now: 
pabsoig_chr12 31180151-31298174_plot

-implemented Highlights feature that allows to define the cut-offs of the x-axis [later changed name to XAxisDefine]

	-removed uniqueID from naming (would create more confusion than help (?))
	-changed the distance between axis ticks to 500,000
		-OBS - may create problems with very small or very large CNVs...
	-implemented SI-measures on x-axis (axis label to K, M for 1000, 1000000 etc...)
		-this requires the script format_si.R that I stole from the internet (but that I reference)

-roxygen2::roxygenise()

Potential issues currently:
	-if more than one file in rawfiledir or downstream it that contains the rawfile-name, it throws an error - might want to changes Files-command to recursive=FALSE
	-for some CNVs, the distance of 0.5 M between ticks might be too little or too much...

Would like to implement:
	-alignment of x-axis ticks with vertical lines of plot

### CODE REVIEW

**Comment by mbertalan** [comment]
Hej Ida ! 

Thanks. Maybe we could remove CNVSD from tittle and include CNV length. What do you think ?

Best,

Marcelo

**Comment by idaElken** [comment]
Hej, 

Since the chr-position and start and stop is there, I think that would be sufficient or?

Any particular reason you would want it?

Cheers, Ida

**Comment by idaElken** [comment]
The reason why I want UniqueID gone is that this number changes based on your CNV-list - and I at least tend to make different lists according to interest (length, chr etc....) and thus it only causes me confusion...

**Comment by mbertalan** [comment]
Yes, we can calculate inside it. Would be nice to have, because SNP number not always reflect CNV length. By the plot is not easy to know CNV length.

**Comment by idaElken** [comment]
Aha, so you mean to put CNV length in the headline of the plot!?! That makes sense. I can implement that now. 

I also see that there is nothing on SDCNV in the headline since I didn't call these CNVs with iPsychCNV - I could also change that even though that doesn't bother me much :-P  


Cheers, Ida

**Comment by idaElken** [comment]
So, with headline I mean:
CN:3, SDCNV: NumSNPs: 37, Sample: PABSOIG
to:
CN:3, SDCNV: NumSNPs: 37, LengthCNV: 500,000, Sample: PABSOIG

When I was talking of UniqueID I was talking of the name of the output-plot...

**Comment by idaElken** [comment]
Ooops, realised that you already waned to remove SDCNV - sorry, reading too sloppily

**Comment by idaElken** [comment]
I'll remove CNVSD and replace it with length :).

**Comment by mbertalan** [comment]
That looks great ! Maybe only length, it is implicit the information is from the CNV.

**Comment by idaElken** [comment]
How about this:
pabsoid_chr15 20301669-20824174_plot

**Comment by idaElken** [comment]
And by the way  - do you know how to align the ticks with the vertical lines of the plots - that would make it easier to read...

**Comment by mbertalan** [comment]
Good, maybe we should use semicolon to separate values and do not mix with length.

**Comment by mbertalan** [comment]
You mean more vertical lines than the original ?

**Comment by idaElken** [comment]
Makes sense but looks a bit messy - will try with space instead :)
pabsoid_chr15 20301669-20824174_plot

**Comment by idaElken** [comment]
With space: 
No preference on my part, really...
pabsoid_chr15 20301669-20824174_plot

**Comment by mbertalan** [comment]
Can you try with tab space and rename NumSNPs to just SNPs ? I think space looks better.

**Comment by idaElken** [comment]
Will try, first tried this:
pabsoid_chr15 20301669-20824174_plot

**Comment by idaElken** [comment]
How to code for tab?
"\t" with paste gives this:
pabsoid_chr15 20301669-20824174_plot

**Comment by mbertalan** [comment]
How about one space for CN: to 3 and 4 spaces for 3 to Size ?

**Comment by idaElken** [comment]
Best so far if you ask me :)
pabsoid_chr15 20301669-20824174_plot

**Comment by mbertalan** [comment]
Good, keep like this.

**Comment by idaElken** [comment]
Will do :)
Did you have an idea as to how to align tick marks and vertical lines of plot?

**Comment by mbertalan** [comment]
No.

**Comment by idaElken** [comment]
Damn it - it would make things easier to look at :-( 
And no, not more lines - just that the vertical lines of the plot are situated with the ticks of the x-axis.
Already wrote to an R-person in our group to ask if he knew - as far as I can tell, most ggplot-plots automatically align but not this one :-(

**Comment by mbertalan** [comment]
http://docs.ggplot2.org/current/theme.html

**Comment by idaElken** [comment]
Thanks, will try to see if there's something there.

**Comment by mbertalan** [comment]
http://www.tengfei.name/ggbio/docs/man/tracks.html
We are using ggbio, so maybe you could send him an email. Also to ask about the CNV plot in the chromosome.

**Comment by idaElken** [comment]
I can try that.

**Comment by idaElken** [comment]
What's tengfei's e-mail?

**Pull request merged**
