### PR TITLE
Updated StackPlot.R

### PR DESCRIPTION
**Pull request by idaElken**
Updated StackPlot.R
-using grep for files in the current version is problematic if there are similar filenames such as: TOP3 TOP34
	-thus changed the command for Files(grep) to solve this issue
	-this included changing default Pattern to ""

BE AWARE that this would also apply to other scripts (ReScanCNV etc). We may want to change this in all scripts in the same way... (saying that mine is most likely not the best scripting)

	-this gave issues with the whole NA-problematics (since no NA-file is fund, the program exits with an error)
	-thus solved this in a possible efficient but likely inadept and clumsy way. :-)

### CODE REVIEW

**Comment by idaElken** [comment]
Sorry - my grep command does not solve the issue - will try again...

**Comment by mbertalan** [comment]
Hej Ida ! Thanks for the comments. In our case all the files have some length, so it should not be a problem. But you are right. However, I would prefer a simpler solution as using which.
which(string == "pattern")

**Comment by mbertalan** [comment]
I modified in StackPlot using which. Please let me know if it works.

**Comment by idaElken** [comment]
Thanks. I'll try

**Comment by idaElken** [comment]
Files[which(Files == paste(PathRawData, "TOP95", Pattern, sep=""))]
seems to work (unless people are like me and happen to have an extra / in the full path:
i.e. 
/Volumes/deCODEdrive/Monster-drive,Decode/RAW_CEL/LRRBAF//TOP95
instead of
 /Volumes/deCODEdrive/Monster-drive,Decode/RAW_CEL/LRRBAF/TOP95

(I can solve that easily - question is if people are equally 'stupid' :-)

I'll see if it also works with the NAs and pull again

**Pull request closed without merging**
